/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    family: Family;
    event: Event;
    invite: Invite;
    list: List;
    item: Item;
    assignment: Assignment;
    exclusion: Exclusion;
    favorite: Favorite;
    message: Message;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      families: 'family';
      lists: 'list';
      invites: 'invite';
    };
    family: {
      invites: 'invite';
      events: 'event';
      favorite: 'favorite';
    };
    event: {
      invites: 'invite';
      assignments: 'assignment';
      exclusions: 'exclusion';
      favorite: 'favorite';
    };
    list: {
      favorite: 'favorite';
    };
    item: {
      list: 'list';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    family: FamilySelect<false> | FamilySelect<true>;
    event: EventSelect<false> | EventSelect<true>;
    invite: InviteSelect<false> | InviteSelect<true>;
    list: ListSelect<false> | ListSelect<true>;
    item: ItemSelect<false> | ItemSelect<true>;
    assignment: AssignmentSelect<false> | AssignmentSelect<true>;
    exclusion: ExclusionSelect<false> | ExclusionSelect<true>;
    favorite: FavoriteSelect<false> | FavoriteSelect<true>;
    message: MessageSelect<false> | MessageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  birthday?: string | null;
  bio?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  avatar?: (string | null) | Media;
  roles?: ('admin' | 'user' | 'super-admin')[] | null;
  families?: {
    docs?: (string | Family)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  lists?: {
    docs?: (string | List)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  invites?: {
    docs?: (string | Invite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family".
 */
export interface Family {
  id: string;
  name: string;
  description?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  members?: (string | User)[] | null;
  allowInvites?: boolean | null;
  managers?: (string | User)[] | null;
  createdBy?: (string | null) | User;
  invites?: {
    docs?: (string | Invite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  inviteLinkToken?: string | null;
  inviteLinkExpiry?: string | null;
  requireApproval?: boolean | null;
  events?: {
    docs?: (string | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  favorite?: {
    docs?: (string | Favorite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite".
 */
export interface Invite {
  id: string;
  email?: string | null;
  token: string;
  tokenExpiry: string;
  eventResponse?: ('declined' | 'maybe' | 'accepted') | null;
  needsApproval?: boolean | null;
  approvalRejected?: boolean | null;
  family?: (string | null) | Family;
  event?: (string | null) | Event;
  user?: (string | null) | User;
  inviter?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event".
 */
export interface Event {
  id: string;
  name: string;
  date?: string | null;
  time?: string | null;
  endDate?: string | null;
  endTime?: string | null;
  location?: string | null;
  info?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  family?: (string | null) | Family;
  creator: string | User;
  managers?: (string | User)[] | null;
  invites?: {
    docs?: (string | Invite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  secretSantaBudget?: string | null;
  secretSantaParticipants?: (string | Invite)[] | null;
  assignments?: {
    docs?: (string | Assignment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  exclusions?: {
    docs?: (string | Exclusion)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  secretSantaNotificationsSent?: boolean | null;
  favorite?: {
    docs?: (string | Favorite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignment".
 */
export interface Assignment {
  id: string;
  event: string | Event;
  giver: string | Invite;
  receiver: string | Invite;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exclusion".
 */
export interface Exclusion {
  id: string;
  event?: (string | null) | Event;
  from?: (string | null) | Invite;
  to?: (string | null) | Invite;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorite".
 */
export interface Favorite {
  id: string;
  user: string | User;
  favorite?:
    | ({
        relationTo: 'family';
        value: string | Family;
      } | null)
    | ({
        relationTo: 'event';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'list';
        value: string | List;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list".
 */
export interface List {
  id: string;
  name: string;
  description?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  user: string | User;
  items?: (string | Item)[] | null;
  public?: boolean | null;
  visibleToFamilies?: (string | Family)[] | null;
  visibleToUsers?: (string | User)[] | null;
  shareLink?: string | null;
  favorite?: {
    docs?: (string | Favorite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item".
 */
export interface Item {
  id: string;
  name: string;
  list: {
    docs?: (string | List)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  link?: string | null;
  notes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priority?: ('low' | 'medium' | 'high') | null;
  price?: string | null;
  image?: (string | null) | Media;
  purchasedBy?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message".
 */
export interface Message {
  id: string;
  content: string;
  sender: string | User;
  family?: (string | null) | Family;
  event?: (string | null) | Event;
  recipient?: (string | null) | User;
  assignment?: (string | null) | Assignment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'family';
        value: string | Family;
      } | null)
    | ({
        relationTo: 'event';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'invite';
        value: string | Invite;
      } | null)
    | ({
        relationTo: 'list';
        value: string | List;
      } | null)
    | ({
        relationTo: 'item';
        value: string | Item;
      } | null)
    | ({
        relationTo: 'assignment';
        value: string | Assignment;
      } | null)
    | ({
        relationTo: 'exclusion';
        value: string | Exclusion;
      } | null)
    | ({
        relationTo: 'favorite';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'message';
        value: string | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  birthday?: T;
  bio?: T;
  avatar?: T;
  roles?: T;
  families?: T;
  lists?: T;
  invites?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "family_select".
 */
export interface FamilySelect<T extends boolean = true> {
  name?: T;
  description?: T;
  members?: T;
  allowInvites?: T;
  managers?: T;
  createdBy?: T;
  invites?: T;
  inviteLinkToken?: T;
  inviteLinkExpiry?: T;
  requireApproval?: T;
  events?: T;
  favorite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_select".
 */
export interface EventSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  time?: T;
  endDate?: T;
  endTime?: T;
  location?: T;
  info?: T;
  family?: T;
  creator?: T;
  managers?: T;
  invites?: T;
  secretSantaBudget?: T;
  secretSantaParticipants?: T;
  assignments?: T;
  exclusions?: T;
  secretSantaNotificationsSent?: T;
  favorite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite_select".
 */
export interface InviteSelect<T extends boolean = true> {
  email?: T;
  token?: T;
  tokenExpiry?: T;
  eventResponse?: T;
  needsApproval?: T;
  approvalRejected?: T;
  family?: T;
  event?: T;
  user?: T;
  inviter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list_select".
 */
export interface ListSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  user?: T;
  items?: T;
  public?: T;
  visibleToFamilies?: T;
  visibleToUsers?: T;
  shareLink?: T;
  favorite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item_select".
 */
export interface ItemSelect<T extends boolean = true> {
  name?: T;
  list?: T;
  link?: T;
  notes?: T;
  priority?: T;
  price?: T;
  image?: T;
  purchasedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignment_select".
 */
export interface AssignmentSelect<T extends boolean = true> {
  event?: T;
  giver?: T;
  receiver?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exclusion_select".
 */
export interface ExclusionSelect<T extends boolean = true> {
  event?: T;
  from?: T;
  to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorite_select".
 */
export interface FavoriteSelect<T extends boolean = true> {
  user?: T;
  favorite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message_select".
 */
export interface MessageSelect<T extends boolean = true> {
  content?: T;
  sender?: T;
  family?: T;
  event?: T;
  recipient?: T;
  assignment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}